### ISSUE TITLE
Improve quality of maintainer images

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/website#52]
It would be nice for the user images to be a bit clearer, in the current format the user images look pixelated.

![image](https://github.com/catppuccin/website/assets/71222764/a3f6b521-2192-464e-aad1-8bac95deb225)

**Comment by andreasgrafen** [comment]
Oh, mh.
I guess we can pull a larger version and then just scale the size in the HTML. That should hopefully resolve this.

**Comment by andreasgrafen** [comment]
@backwardspy
> requesting 128px avatars transfers 2.8 MB
> requesting 256px avatars transfers 3.3 MB
> allowing github to send max (up to 480 px it seems) transfers 4.4 MB

Since GitHub doesn't serve .webp the file size is kind of an issue tho.
It may be worth to look into a solution where we pull the images on build time and embed them locally as .webp files.

**Comment by sgoudham** [comment]
> It may be worth to look into a solution where we pull the images on build time and embed them locally as .webp files.

I tested this out locally and actually found there was no worthwhile difference.

**GitHub URLs with `size=128`** (currently in production):
![image](https://github.com/catppuccin/website/assets/58985301/f6331aa9-d59a-49ec-87d7-312efa822836)

**GitHub URLs with `size=256`**:
![image](https://github.com/catppuccin/website/assets/58985301/152e65f9-233a-4f3c-995f-8016c247fe25)

**WEBP images stored in the `public/` directory**
(downloading `size=512` and converting with `convert <png> -quality 80 <webp>`):
![image](https://github.com/catppuccin/website/assets/58985301/660a283a-ff29-4828-9826-ab7d4298932b)

Two things to consider:
1. Using GitHub URLs means the byte size scales `O(n)` where `n` is the maintainer count. It is worth noting that not all of the MBs is loaded at once since the browser only fetches as it needs to when you scroll down.
2. Using WEBPs means that we can improve quality while decreasing MBs, but it means that the PFPs are vendored and do not automatically update when a user on GitHub changes their profile picture. 

Personally, I think we should go for just bumping the size of the url to `size=256` and go from there to improve the quality of the images on the current webpage. We're not in danger of reaching the non-authenticated GitHub rate limit yet as it can still withstand a force refresh and 4/5 times scrolling down top to bottom. This will only become a problem if we have over thousand maintainers.
